#!/bin/bash
# info.sh - system info
RED='\033[0;31m'; NC='\033[0m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; WHITE='\033[1;37m'
MYIP=$(cat /etc/fazzpedia/myip 2>/dev/null || curl -s ipinfo.io/ip)
svc() { systemctl is-active --quiet "$1" && echo -e "${GREEN}[RUNNING]${NC}" || echo -e "${RED}[STOPPED]${NC}"; }
clear
echo -e "${CYAN}============================================================${NC}"
echo -e "${YELLOW}         FazzPedia||Vpn - System Information${NC}"
echo -e "${CYAN}============================================================${NC}"
echo -e " ${WHITE}IP Address  : ${YELLOW}$MYIP${NC}"
echo -e " ${WHITE}OS          : ${YELLOW}$(lsb_release -ds 2>/dev/null)${NC}"
echo -e " ${WHITE}Kernel      : ${YELLOW}$(uname -r)${NC}"
echo -e " ${WHITE}Uptime      : ${YELLOW}$(uptime -p)${NC}"
echo -e " ${WHITE}CPU         : ${YELLOW}$(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | xargs) ($(nproc) cores)${NC}"
echo -e " ${WHITE}CPU Usage   : ${YELLOW}$(top -bn1 | grep 'Cpu(s)' | awk '{print $2}')%${NC}"
echo -e " ${WHITE}RAM         : ${YELLOW}$(free -m | awk 'NR==2{printf "%s/%s MB", $3,$2}')${NC}"
echo -e " ${WHITE}Disk        : ${YELLOW}$(df -h / | awk 'NR==2{printf "%s/%s", $3,$2}')${NC}"
echo -e "${CYAN}──────────────── Services ───────────────────${NC}"
echo -e " SSH             :$(svc ssh)"
echo -e " Dropbear        :$(svc dropbear)"
echo -e " Stunnel4        :$(svc stunnel4)"
echo -e " SSLH            :$(svc sslh)"
echo -e " OpenVPN TCP     :$(svc openvpn@server-tcp)"
echo -e " OpenVPN UDP     :$(svc openvpn@server-udp)"
echo -e " Squid           :$(svc squid)"
echo -e " Xray            :$(svc xray)"
echo -e " Wireguard       :$(svc wg-quick@wg0)"
echo -e " WebSocket NTLS  :$(svc ws-nontls)"
echo -e "${CYAN}──────────────── Ports ──────────────────────${NC}"
echo -e " SSH         : 22, 2253"
echo -e " Dropbear    : 109, 143"
echo -e " SSLH        : 443"
echo -e " Stunnel SSL : 445, 777, 990"
echo -e " OpenVPN     : TCP 1194, UDP 2200"
echo -e " Squid       : 3128, 8080"
echo -e " BadVPN      : 7100, 7200, 7300"
echo -e " Wireguard   : 7070"
echo -e " L2TP/IPSec  : 1701"
echo -e " SSTP        : 444"
echo -e " VMess TLS   : 8443"
echo -e " VMess NTLS  : 80"
echo -e " VLess TLS   : 8442"
echo -e " VLess NTLS  : 8441"
echo -e " Trojan      : 2083"
echo -e " WS Non-TLS  : 8880"
echo -e " OHP SSH     : 8181"
echo -e " OHP DB      : 8282"
echo -e " OHP OVPN    : 8383"
echo -e "${CYAN}============================================================${NC}"
